### ISSUE TITLE
m2-hsio-module support

### ISSUE THREAD

**Issue by AEW2015** [Avnet/ZUBoard_1CG-PYNQ#1]
I am going to try to add support for the m2-hsio-module.
Is there any known issue for this?

http://avnet.me/m2-hsio-module

**Comment by FredKellerman** [comment]
None "known" at this time.  Has not been used with this PYNQ build, I don't know of any reason why it wouldn't work.

Are you going to just use PYNQ Python to use it, and requesting to fully integrate it into PetaLinux and the PYNQ SD card release?

**Comment by AEW2015** [comment]
It needs to be added to the device tree, and PCIe tools (like lspci) need to be included in the build.
I attempted to do it, but I need to install the correct version of all the tools...
It would be great if the official build supported M2 and/or DP HSIO modules.
It's on my to-do list, I will fork/ pull-request if I get a working build.

**Comment by AlbertaBeef** [comment]
Andrew,

One known issue:
- the M.2 HSIO must be placed on the J2 connector, since it requires the lower transceiver lanes for the PCI express functionality.

This is described in the following project:
- https://avnet.me/vitis-ai-3.0-hailo-8

Regards,
Mario.

**Comment by FredKellerman** [comment]
Hi, My only request is: that we do it in some manner that is compatible with and without the add-on card, preferably all in a single SD card release image.  Meaning not managed by compiling 2 different branches if possible.

I don't have time right now to do it all but I can help you.  At this time I do not even have an HSIO card but I could get one.

The device tree and kernel options can be modified through the use of the content under here: https://github.com/Avnet/ZUBoard_1CG-PYNQ/tree/main/ZUBoard_1CG/petalinux_bsp/meta-user  Start there, if it gets to messy we can consider other ways.  PYNQ packages might need to be used if device drivers need to be patched or modified.

If you have @AlbertaBeef direct contact already, he can give you mine as well so we can communicate more efficiently.

Kind regards,
+Fred

**Comment by AEW2015** [comment]
Well adding PCIe to the block diagram and device tree is not enough....
![image](https://github.com/Avnet/ZUBoard_1CG-PYNQ/assets/12721146/db3b0db3-a20c-4fd9-be12-81d4d3caafe8)

**Comment by FredKellerman** [comment]
Hi Andrew,  The bsp that PYNQ is built off of is minimal.  You could take a look at the @AlbertaBeef bsp that was shared through the Hailo Hackster project and determine which additional modules are needed.  It is usually easier and sufficient to add addtional modules in the bsp.cfg file under the meta-user layer in this repo for PYNQ.  PYNQ was not updated this year so you will need v2022.1 PetaLinux, Vivado and it will be the least amount of trouble to use Ubuntu 20.04 LTS.

**Comment by AEW2015** [comment]
I got pcie working, but the `lspci` util is missing.
Just added following to: https://github.com/Xilinx/PYNQ/blob/image_v3.0.1/sdbuild/Makefile#L179
`petalinux-config --get-hw-description /home/farmer/bsps/ZUBoard_1CG-PYNQ/ZUBoard_1CG/ZUBoard_1CGOverlay/ZUBoard_1CGOverlay.xsa --silentconfig -p $$(PL_PROJ_$1)`
![pynq_lspci](https://github.com/Avnet/ZUBoard_1CG-PYNQ/assets/12721146/12c4253e-28e4-4330-ac27-4f63d034aa82)
![pynq_pcie](https://github.com/Avnet/ZUBoard_1CG-PYNQ/assets/12721146/d52bff34-9965-42e5-9d2e-b8789ab6d23a)

**Comment by FredKellerman** [comment]
Excellent, makes me smile :-)  None of the PYNQ boards have the ability to connect to anything PCIe, ZU Board didn't at first either.  So not surprised missing a few things.

Is there something in your PL that is needed to make the HSIO m.2 PCIe work?  I was not involved with the HSIO m.2 design and never looked into it.  So I'm assuming the PCIe is all managed from the PS.  The PYNQ sd image doesn't load any PL when it starts up but boot.py can be modified to load any Overlay/bitstream when it boots up.

**Comment by AEW2015** [comment]
It is just a small modification to the PS configuration in the block diagram/ tcl.  This enables the PCIe for the PS and adds it the device tree.  This should also add lspci to the rootfs, but PYNQ drops that rootfs for their version.  Trying to figure out how to bring pciutils up to the main rootfs.  This is a PS only configuration and it is normally not affected by the bitstream.  If the "second" slot was used for the display port, that doesn't have all mmio, but some emio pins.  That one may require a bitstream for the display port/ eMMC HSIO module.

**Comment by FredKellerman** [comment]
Do you know yet which packages are missing from the PYNQ Ubuntu rootfs, you mentioned pc utils?  It's to late for this PYNQ release but I can ask AMD to include it for the next one.

I would guess lspci requires kernel headers to compile?  If not, you could probabaly just clone and build lspci on the ZU1.

Otherwise, it could be built in as a pynq package which has access to the kernel headers.  This Ultra96 example shows how the scripting works to customize the rootfs:  https://github.com/Avnet/Ultra96-PYNQ/tree/master/Ultra96/packages/wilc3000  

With respect to the Vivado changes, sounds like would just need to change a few lines of tcl in the base overlay, update the minimal bsp with it and rebuild?

**Comment by AEW2015** [comment]
I think it is just pciutils and will try building it locally on the ZUBoard to see if that is enough.  
I will also try installing xdma for interacting with the 2nd FPGA over m.2 PCIe.
I will also try some other PCIe devices like NVMe SSD.
Any other M.2 devices I should try?

I also have the Display Port and eMMC module, I want to get that working too.

**Comment by AEW2015** [comment]
A local build of pciutils worked great:
```
git clone https://github.com/pciutils/pciutils.git
cd ./ pciutils
make
sudo make install
sudo lspci -v
```
![image](https://github.com/Avnet/ZUBoard_1CG-PYNQ/assets/12721146/54ba2799-debd-42d4-80ba-d39f8413dc23)
